services:
  srv:
    build: .
    restart: always
    stop_signal: SIGINT
    ports:
      - 9876:9876/udp
      - 9877:9877/udp
    volumes:
      - data:/mnt/AppData
      - ./config:/mnt/AppData/Settings
    command:
      - -persistentDataPath
      - /mnt/AppData

volumes:
  data: {}
